### ISSUE TITLE
Failed to invoke function `fkr.person`: Caused by: java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jotamotk** [neo4j-contrib/neo4j-faker#4]
Hi there,
After installation, I can run http://127.0.0.1:7474/testdata/tdg/pfile/test.props?dbname=mydb successfully.

But now, I am trying to use example query to generate 1000 person nodes, which result in "Failed to invoke function `fkr.person`: Caused by: java.lang.StringIndexOutOfBoundsException", can anyone help?

I am using query:
foreach (i in range(0,1000) |
    create (p:Person { uid : i })
    set p += fkr.person('1960-01-01','2000-01-01')
)

**Comment by kvegter** [comment]
This is solved in version 0.9.2
